### ISSUE TITLE
ImportError: No module named gnomekeyring

### ISSUE THREAD

**Issue by brianjmurrell** [kparal/gkeyring#12]
On Fedora 27:

```bash
$ pip install --upgrade --user gkeyring
Collecting gkeyring
  Downloading https://files.pythonhosted.org/packages/6c/0a/9ef736875004442ccdc1f87f8c5896fb7853028125a9bdcb2e1fbb51ce06/gkeyring-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/brian/tmp/pip-build-3wcDsu/gkeyring/setup.py", line 4, in <module>
        import gkeyring
      File "gkeyring.py", line 21, in <module>
        import gnomekeyring as gk
    ImportError: No module named gnomekeyring
```

**Comment by kparal** [comment]
You need to install `gnome-python2-gnomekeyring` from Fedora repos.

**Comment by brianjmurrell** [comment]
Strange.  Is there a reason why `pip install` of this module doesn't pull in the gnomekeyring python module from PyPI also?  Maybe GNOME are not publishing it?

Thanks for the response in any case.

**Comment by kparal** [comment]
It's not set as a dependency (just look into setup.py) and I haven't looked whether it's in pypi, really. It's a native C module, fwiw.
